# Generated by Django 3.1.7 on 2021-04-22 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210422_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to='network.post'),
        ),
    ]
