# Generated by Django 3.1.7 on 2021-04-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20210422_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='test',
            field=models.ManyToManyField(to='network.Post'),
        ),
    ]
