# Generated by Django 3.1.7 on 2021-04-22 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_profile_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='test',
        ),
    ]
