# Generated by Django 3.1.7 on 2021-04-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_profile_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='test',
            field=models.ManyToManyField(blank=True, to='network.Post'),
        ),
    ]
