# Generated by Django 3.1.7 on 2021-03-12 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=64)),
                ('timeCreated', models.DateTimeField()),
            ],
            bases=(models.Model, datetime.date),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=64)),
                ('item', models.ManyToManyField(blank=True, related_name='comments', to='auctions.Listing')),
            ],
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField()),
                ('bid', models.ManyToManyField(blank=True, related_name='bids', to='auctions.Listing')),
            ],
        ),
    ]
