# Generated by Django 3.1.7 on 2021-03-12 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210312_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid',
            new_name='item',
        ),
    ]
